{{- range $env := .Values.environments }}
{{- range $serviceconf := $env.deployments }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $serviceconf.name }}-{{ $env.name }}-deployment
  namespace: cluster-configuration
spec:
  selector:
    matchLabels:
      app: {{ $serviceconf.name }}
  template:
    metadata:
      labels:
        app: {{ $serviceconf.name }}
        target-namespace: {{ $env.name }}
    spec:
      containers:
        - name: {{ $serviceconf.name }}-container
          imagePullPolicy: Never
          image: asmhttp:latest 
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceconf.name }}-{{ $env.name }}-deployment
  namespace: cluster-configuration
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ $serviceconf.name }}
---
{{- end }}
{{- end }}
